site_name: Making Discord Bots
site_url: https://r0bl0x10501050.github.io/making-discord-bots
repo_name: R0bl0x10501050/Making-Discord-Bots
repo_url: https://github.com/R0bl0x10501050/Making-Discord-Bots

theme:
  name: material
  palette:
  
  # Light mode
    - light blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Turn Off The Lights

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Turn On The Lights

nav:
  - Home: index.md
  - Tutorial: docs.md
    
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
